-- MySQL Script generated by MySQL Workbench
-- Tue Jun 19 17:20:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bancodedados
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bancodedados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancodedados` DEFAULT CHARACTER SET utf8 COLLATE utf8_danish_ci ;
USE `bancodedados` ;

-- -----------------------------------------------------
-- Table `bancodedados`.`endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodedados`.`endereço` (
  `cpf` INT NOT NULL,
  `rua` VARCHAR(100) NULL,
  `numero` TINYINT(4) NULL,
  `bairro` VARCHAR(45) NULL,
  `cep` VARCHAR(9) NULL,
  `cidade` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bancodedados`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodedados`.`telefone` (
  `cpf` INT NOT NULL,
  `numero` VARCHAR(20) NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bancodedados`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodedados`.`usuario` (
  `cpf` INT NOT NULL,
  `rg` INT NULL,
  `nome` VARCHAR(60) NULL,
  `e-mail` VARCHAR(45) NULL,
  `endereço_cpf` INT NOT NULL,
  `telefone_cpf` INT NOT NULL,
  PRIMARY KEY (`cpf`, `endereço_cpf`, `telefone_cpf`),
  INDEX `fk_usuario_endereço1_idx` (`endereço_cpf` ASC),
  INDEX `fk_usuario_telefone1_idx` (`telefone_cpf` ASC),
  CONSTRAINT `fk_usuario_endereço1`
    FOREIGN KEY (`endereço_cpf`)
    REFERENCES `bancodedados`.`endereço` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_telefone1`
    FOREIGN KEY (`telefone_cpf`)
    REFERENCES `bancodedados`.`telefone` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bancodedados`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodedados`.`professor` (
  `cod disciplina` INT NULL,
  `nome disciplina` VARCHAR(45) NULL,
  `cpf` INT NOT NULL,
  `usuario_cpf` INT NOT NULL,
  PRIMARY KEY (`cpf`, `usuario_cpf`),
  INDEX `fk_professor_usuario1_idx` (`usuario_cpf` ASC),
  CONSTRAINT `fk_professor_usuario1`
    FOREIGN KEY (`usuario_cpf`)
    REFERENCES `bancodedados`.`usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancodedados`.`c.materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodedados`.`c.materia` (
  `cod disciplina` INT NULL,
  `nome disciplina` VARCHAR(45) NULL,
  `cpf` INT NOT NULL,
  `usuario_cpf` INT NOT NULL,
  `usuario_cpf1` INT NOT NULL,
  `usuario_endereço_cpf` INT NOT NULL,
  `usuario_telefone_cpf` INT NOT NULL,
  `professor_cpf` INT NOT NULL,
  `professor_usuario_cpf` INT NOT NULL,
  PRIMARY KEY (`cpf`, `usuario_cpf`, `usuario_cpf1`, `usuario_endereço_cpf`, `usuario_telefone_cpf`, `professor_cpf`, `professor_usuario_cpf`),
  INDEX `fk_c.materia_usuario_idx` (`usuario_cpf` ASC),
  INDEX `fk_c.materia_usuario1_idx` (`usuario_cpf1` ASC, `usuario_endereço_cpf` ASC, `usuario_telefone_cpf` ASC),
  INDEX `fk_c.materia_professor1_idx` (`professor_cpf` ASC, `professor_usuario_cpf` ASC),
  CONSTRAINT `fk_c.materia_usuario`
    FOREIGN KEY (`usuario_cpf`)
    REFERENCES `bancodedados`.`usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_c.materia_usuario1`
    FOREIGN KEY (`usuario_cpf1` , `usuario_endereço_cpf` , `usuario_telefone_cpf`)
    REFERENCES `bancodedados`.`usuario` (`cpf` , `endereço_cpf` , `telefone_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_c.materia_professor1`
    FOREIGN KEY (`professor_cpf` , `professor_usuario_cpf`)
    REFERENCES `bancodedados`.`professor` (`cpf` , `usuario_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bancodedados`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodedados`.`disciplina` (
  `cod disciplina` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`cod disciplina`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bancodedados`.`colegio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodedados`.`colegio` (
  `idcolegio` INT NULL,
  `cpf` INT NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancodedados`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodedados`.`aluno` (
  `lingua estrangeira` VARCHAR(10) NULL,
  `numero matricula` INT NULL,
  `cpf` INT NOT NULL,
  `usuario_cpf` INT NOT NULL,
  `colegio_cpf` INT NOT NULL,
  `usuario_cpf1` INT NOT NULL,
  `usuario_endereço_cpf` INT NOT NULL,
  `usuario_telefone_cpf` INT NOT NULL,
  PRIMARY KEY (`cpf`, `usuario_cpf`, `colegio_cpf`, `usuario_cpf1`, `usuario_endereço_cpf`, `usuario_telefone_cpf`),
  INDEX `fk_aluno_usuario1_idx` (`usuario_cpf` ASC),
  INDEX `fk_aluno_colegio1_idx` (`colegio_cpf` ASC),
  INDEX `fk_aluno_usuario2_idx` (`usuario_cpf1` ASC, `usuario_endereço_cpf` ASC, `usuario_telefone_cpf` ASC),
  CONSTRAINT `fk_aluno_usuario1`
    FOREIGN KEY (`usuario_cpf`)
    REFERENCES `bancodedados`.`usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_colegio1`
    FOREIGN KEY (`colegio_cpf`)
    REFERENCES `bancodedados`.`colegio` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_usuario2`
    FOREIGN KEY (`usuario_cpf1` , `usuario_endereço_cpf` , `usuario_telefone_cpf`)
    REFERENCES `bancodedados`.`usuario` (`cpf` , `endereço_cpf` , `telefone_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bancodedados`.`simulado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodedados`.`simulado` (
  `numero matricula` INT NOT NULL,
  `nota` VARCHAR(45) NULL,
  `aluno_cpf` INT NOT NULL,
  `aluno_usuario_cpf` INT NOT NULL,
  `aluno_colegio_cpf` INT NOT NULL,
  `aluno_usuario_cpf1` INT NOT NULL,
  `aluno_usuario_endereço_cpf` INT NOT NULL,
  `aluno_usuario_telefone_cpf` INT NOT NULL,
  PRIMARY KEY (`numero matricula`, `aluno_cpf`, `aluno_usuario_cpf`, `aluno_colegio_cpf`, `aluno_usuario_cpf1`, `aluno_usuario_endereço_cpf`, `aluno_usuario_telefone_cpf`),
  INDEX `fk_simulado_aluno1_idx` (`aluno_cpf` ASC, `aluno_usuario_cpf` ASC, `aluno_colegio_cpf` ASC, `aluno_usuario_cpf1` ASC, `aluno_usuario_endereço_cpf` ASC, `aluno_usuario_telefone_cpf` ASC),
  CONSTRAINT `fk_simulado_aluno1`
    FOREIGN KEY (`aluno_cpf` , `aluno_usuario_cpf` , `aluno_colegio_cpf` , `aluno_usuario_cpf1` , `aluno_usuario_endereço_cpf` , `aluno_usuario_telefone_cpf`)
    REFERENCES `bancodedados`.`aluno` (`cpf` , `usuario_cpf` , `colegio_cpf` , `usuario_cpf1` , `usuario_endereço_cpf` , `usuario_telefone_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bancodedados`.`coordenador geral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodedados`.`coordenador geral` (
  `cpf` INT NOT NULL,
  `usuario_cpf` INT NOT NULL,
  `disciplina_cod disciplina` INT NOT NULL,
  `simulado_numero matricula` INT NOT NULL,
  `c.materia_cpf` INT NOT NULL,
  `c.materia_usuario_cpf` INT NOT NULL,
  `c.materia_usuario_cpf1` INT NOT NULL,
  `c.materia_usuario_endereço_cpf` INT NOT NULL,
  `c.materia_usuario_telefone_cpf` INT NOT NULL,
  `c.materia_professor_cpf` INT NOT NULL,
  `c.materia_professor_usuario_cpf` INT NOT NULL,
  PRIMARY KEY (`cpf`, `usuario_cpf`, `disciplina_cod disciplina`, `simulado_numero matricula`, `c.materia_cpf`, `c.materia_usuario_cpf`, `c.materia_usuario_cpf1`, `c.materia_usuario_endereço_cpf`, `c.materia_usuario_telefone_cpf`, `c.materia_professor_cpf`, `c.materia_professor_usuario_cpf`),
  INDEX `fk_coordenador geral_usuario1_idx` (`usuario_cpf` ASC),
  INDEX `fk_coordenador geral_disciplina1_idx` (`disciplina_cod disciplina` ASC),
  INDEX `fk_coordenador geral_simulado1_idx` (`simulado_numero matricula` ASC),
  INDEX `fk_coordenador geral_c.materia1_idx` (`c.materia_cpf` ASC, `c.materia_usuario_cpf` ASC, `c.materia_usuario_cpf1` ASC, `c.materia_usuario_endereço_cpf` ASC, `c.materia_usuario_telefone_cpf` ASC, `c.materia_professor_cpf` ASC, `c.materia_professor_usuario_cpf` ASC),
  CONSTRAINT `fk_coordenador geral_usuario1`
    FOREIGN KEY (`usuario_cpf`)
    REFERENCES `bancodedados`.`usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coordenador geral_disciplina1`
    FOREIGN KEY (`disciplina_cod disciplina`)
    REFERENCES `bancodedados`.`disciplina` (`cod disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coordenador geral_simulado1`
    FOREIGN KEY (`simulado_numero matricula`)
    REFERENCES `bancodedados`.`simulado` (`numero matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coordenador geral_c.materia1`
    FOREIGN KEY (`c.materia_cpf` , `c.materia_usuario_cpf` , `c.materia_usuario_cpf1` , `c.materia_usuario_endereço_cpf` , `c.materia_usuario_telefone_cpf` , `c.materia_professor_cpf` , `c.materia_professor_usuario_cpf`)
    REFERENCES `bancodedados`.`c.materia` (`cpf` , `usuario_cpf` , `usuario_cpf1` , `usuario_endereço_cpf` , `usuario_telefone_cpf` , `professor_cpf` , `professor_usuario_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bancodedados`.`professor_has_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodedados`.`professor_has_disciplina` (
  `professor_cpf` INT NOT NULL,
  `professor_usuario_cpf` INT NOT NULL,
  `disciplina_cod disciplina` INT NOT NULL,
  PRIMARY KEY (`professor_cpf`, `professor_usuario_cpf`, `disciplina_cod disciplina`),
  INDEX `fk_professor_has_disciplina_disciplina1_idx` (`disciplina_cod disciplina` ASC),
  INDEX `fk_professor_has_disciplina_professor1_idx` (`professor_cpf` ASC, `professor_usuario_cpf` ASC),
  CONSTRAINT `fk_professor_has_disciplina_professor1`
    FOREIGN KEY (`professor_cpf` , `professor_usuario_cpf`)
    REFERENCES `bancodedados`.`professor` (`cpf` , `usuario_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_has_disciplina_disciplina1`
    FOREIGN KEY (`disciplina_cod disciplina`)
    REFERENCES `bancodedados`.`disciplina` (`cod disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancodedados`.`professor_has_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodedados`.`professor_has_aluno` (
  `professor_cpf` INT NOT NULL,
  `professor_usuario_cpf` INT NOT NULL,
  `aluno_cpf` INT NOT NULL,
  `aluno_usuario_cpf` INT NOT NULL,
  `aluno_colegio_cpf` INT NOT NULL,
  `aluno_usuario_cpf1` INT NOT NULL,
  `aluno_usuario_endereço_cpf` INT NOT NULL,
  `aluno_usuario_telefone_cpf` INT NOT NULL,
  PRIMARY KEY (`professor_cpf`, `professor_usuario_cpf`, `aluno_cpf`, `aluno_usuario_cpf`, `aluno_colegio_cpf`, `aluno_usuario_cpf1`, `aluno_usuario_endereço_cpf`, `aluno_usuario_telefone_cpf`),
  INDEX `fk_professor_has_aluno_aluno1_idx` (`aluno_cpf` ASC, `aluno_usuario_cpf` ASC, `aluno_colegio_cpf` ASC, `aluno_usuario_cpf1` ASC, `aluno_usuario_endereço_cpf` ASC, `aluno_usuario_telefone_cpf` ASC),
  INDEX `fk_professor_has_aluno_professor1_idx` (`professor_cpf` ASC, `professor_usuario_cpf` ASC),
  CONSTRAINT `fk_professor_has_aluno_professor1`
    FOREIGN KEY (`professor_cpf` , `professor_usuario_cpf`)
    REFERENCES `bancodedados`.`professor` (`cpf` , `usuario_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_has_aluno_aluno1`
    FOREIGN KEY (`aluno_cpf` , `aluno_usuario_cpf` , `aluno_colegio_cpf` , `aluno_usuario_cpf1` , `aluno_usuario_endereço_cpf` , `aluno_usuario_telefone_cpf`)
    REFERENCES `bancodedados`.`aluno` (`cpf` , `usuario_cpf` , `colegio_cpf` , `usuario_cpf1` , `usuario_endereço_cpf` , `usuario_telefone_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
